version: '3.8'

services:
  ecs_app:
    build:
      context: .
      dockerfile: ./docker/staging/rails/Dockerfile
    volumes:
      - .:/usr/src/app/:cached
      # nginx から sockets を扱えるようにマウントする
      - web-sockets-data:/usr/src/app/tmp/sockets
    environment:
      DB_HOST: "${DB_HOST}"
      REDIS: "${REDIS}"
    tty: true
    stdin_open: true
  ecs_web:
    build:
      context: .
      dockerfile: ./docker/staging/nginx/Dockerfile
    volumes:
      - web-sockets-data:/usr/src/app/tmp/sockets
    ports:
      - "80:80"
    depends_on:
      - ecs_app
  ecs_worker:
    build:
      context: .
      dockerfile: ./docker/staging/sidekiq/Dockerfile
    volumes:
      - .:/usr/src/app/:cached
    environment:
      DB_HOST: "${DB_HOST}"
      REDIS: "${REDIS}"
    # コンテナ永続させる
    # https://zenn.dev/hohner/articles/43a0da20181d34
    tty: true
    # 標準入出力とエラー出力をコンテナに結びつける
    stdin_open: true

volumes:
  web-sockets-data:
