version: '3'

services:
  db:
    image: mysql:5.6.44
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "4306:3306"
    volumes:
      - ./tmp/mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: >
      bash -c "rm -rf tmp/pids/server.pid &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/:cached
    environment:
      DB_HOST: db
      RAILS_ENV: development
      SELENIUM_DRIVER_URL: 'http://chrome:4444/wd/hub'
      REDIS: 'redis://redis:6379'
    depends_on:
      - db
      - redis
      - worker
      - chrome
    tty: true
    stdin_open: true
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    depends_on:
      - db
  worker:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app/:cached
    environment:
      DB_HOST: db
      RAILS_ENV: development
      REDIS: 'redis://redis:6379'
    depends_on:
      - redis
  chrome:
    image: selenium/standalone-chrome:3.141.59-zirconium
    volumes:
      - /dev/shm:/dev/shm

volumes:
  redis-data:
    driver: local
