***REMOVED***
  adapter: async

***REMOVED***
  adapter: test

***REMOVED***
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: christchurches_map_production
